<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBnMfNaB\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBnMfNaB/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBnMfNaB.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBnMfNaB\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerBnMfNaB\App_KernelDevDebugContainer([
    'container.build_hash' => 'BnMfNaB',
    'container.build_id' => '24c72a5e',
    'container.build_time' => 1611142200,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBnMfNaB');
